version: "3.3"

services:
    ezmanager:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: ezmanager
        container_name: ezmanager
        restart: always
        ports:
            - 3000:3000
    webserver:
        image: nginx:mainline-alpine
        container_name: webserver
        restart: always
        ports:
            - 80:80
        volumes:
            - ./nginx-conf:/etc/nginx/conf.d
